title:            newbiettn
description:      Standing on the shoulders of giants
#url:              http://127.0.0.1:4000
url:              https://ngoctran.me
enforce_ssl:      ngoctran.me
signoff:          Ngoc Tran
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Home
    url:          /
  - name:         Maths
    url:          /maths
  - name:         About
    url:          /about

permalink:        pretty
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
